---

runners:
  default:
    timeout: 5m
    # response_ok: "OK"
    response_ok: "↑"  # any unicode string can be used, '↑' is just an example
    # response_fail: "FAILED"
    # response_timeout: "TIMEOUT"
  cli: {}  # override default runner only for CLI mode
  http:  # override default runner only for HTTP mode
    listen_address: "127.0.0.1:51234"
    # shutdown_signal_header is mainly useful for testing http mode,
    # do not set it in production
    # if set, better be treated like a secret, and a secure transport
    # layer should be used.
    # this is the value set on "X-Shutdown-Signal" header in the http request
    # shutdown_signal_header: "test-shutdown-signal"
    # request_read_timeout: 2s
    # response_write_timeout: 2s
    # timeout: 5s
    # max_header_bytes: 8192
    # max_concurrent_requests: 1  # 0 means no limit
    # request_required_headers:
    #   "X-Required-Header": "required-value"
    #   "X-Required-Header2": ""  # header existance is required, not value


check_suites:
  etc:
    - type: dir
      path: /etc
      mode: 0755
      user: root
      group: root
    - type: file
      path: /etc/passwd
      min_size: 10
    - type: file
      path: /etc/group
      min_size: 5
      max_size: 10
  default:
    - type: file
      path: /unwanted/file
      absent: true
    - type: dial
      network: tcp
      address: "localhost:8080"
      absent: true
      timeout: 500ms
    - type: dial
      network: tcp
      address: "localhost:80"
      timeout: 500ms

...
