---

name: tests

on:   # yamllint disable-line rule:truthy
  push: {}
  pull_request:
    branches: [main]

permissions:
  contents: read

jobs:
  tests-go-1.24:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-go@v6
        with:
          go-version: 1.24

      - name: Verify dependencies
        run: go mod verify

      - name: Run go vet
        run: go vet ./...

      - name: Build
        run: go build -v cmd/*

      - name: Run tests
        run: go test -race -vet=off ./...

  tests-go.126:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-go@v6
        with:
          go-version: 1.26

      - name: Verify dependencies
        run: go mod verify

      - name: Run go vet
        run: go vet ./...

      - name: Build
        run: go build -v cmd/*

      - name: Run tests
        run: go test -race -vet=off ./...
